# Generated by Django 4.1.1 on 2023-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produits_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.AlterModelOptions(
            name='produits',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='date_expiration',
        ),
        migrations.AddField(
            model_name='categories',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
