# Generated by Django 4.1.1 on 2023-10-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_categories_options_alter_produits_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
