# Generated by Django 4.1.1 on 2023-10-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_categories_produits_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
