# Generated by Django 4.1.1 on 2023-10-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_delete_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produits')),
            ],
        ),
    ]
