# Generated by Django 4.1.1 on 2023-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodComd', models.CharField(max_length=300)),
                ('nom_cli', models.CharField(max_length=128)),
                ('email_cli', models.EmailField(max_length=254)),
                ('Tel_cli', models.IntegerField(max_length=9)),
                ('ville_cli', models.CharField(max_length=128)),
                ('quart_cli', models.CharField(max_length=128)),
                ('adress_cli', models.CharField(max_length=128)),
                ('zip', models.CharField(max_length=128)),
                ('date_commande', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
