# Generated by Django 4.1.1 on 2023-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant',
            field=models.CharField(default='00', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='Tel_cli',
            field=models.IntegerField(),
        ),
    ]
